spring.application.name=sprintiq

## DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sprintiq
spring.datasource.username=root
spring.datasource.password=root

## JPA configuration
# spring.jpa.hibernate.ddl-auto=update

## Init DB
# spring.sql.init.mode=always
## Initiate DB
# spring.sql.init.data-locations=classpath:sql/initiate_db.sql
## Initiate DB and add sample data
# spring.sql.init.data-locations=classpath:sql/initiate_db.sql,classpath:sql/add_sample_records.sql

## JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
